medical_warehouse:
  outputs:
    dev:
      dbname: medical_warehouse
      host: localhost
      pass: '12345678'
      port: 5432
      schema: raw
      threads: 1
      type: postgres
      user: postgres
  target: dev
