version: 2

models:
  - name: dim_channels
    description: "Dimension table for Telegram channels"
    columns:
      - name: channel_key
        description: "Surrogate key for channel"
        tests:
          - unique
          - not_null
      - name: channel_name
        description: "Name of the channel"
        tests:
          - unique
          - not_null
      - name: total_posts
        description: "Total number of posts in channel"
        tests:
          - not_null

  - name: dim_dates
    description: "Date dimension table"
    columns:
      - name: date_key
        description: "Surrogate key for date"
        tests:
          - unique
          - not_null
      - name: full_date
        tests:
          - not_null

  - name: fct_messages
    description: "Fact table for messages"
    columns:
      - name: message_id
        tests:
          - unique
          - not_null
      - name: channel_key
        tests:
          - relationships:
              arugments:
              to: ref('dim_channels')
              field: channel_key
      - name: date_key
        tests:
          - relationships:
              to: ref('dim_dates')
              field: date_key
      - name: view_count
        tests:
          - not_null