version: 2

models:
  - name: dim_channels
    description: "Dimension table for Telegram channels"
    columns:
      - name: channel_key
        description: "Surrogate key for channel"
        data_tests:
          - unique
          - not_null
      - name: channel_name
        description: "Name of the channel"
        data_tests:
          - unique
          - not_null
      - name: total_posts
        description: "Total number of posts in channel"
        data_tests:
          - not_null

  - name: dim_dates
    description: "Date dimension table"
    columns:
      - name: date_key
        description: "Surrogate key for date"
        data_tests:
          - unique
          - not_null
      - name: full_date
        data_tests:
          - not_null

  - name: fct_messages
    description: "Fact table for messages"
    columns:
      - name: message_id
        data_tests:
          - unique
          - not_null
      - name: channel_key
        data_tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_channels')
                field: channel_key
      - name: date_key
        data_tests:
          - relationships:
              arguments:
                to: ref('dim_dates')
                field: date_key
      - name: view_count
        data_tests:
          - not_null
  - name: stg_telegram_messages
    columns:
      - name: message_id
        data_tests:
          - unique
          - not_null
      - name: channel_name
        data_tests:
          - not_null
      - name: message_date
        data_tests:
          - not_null
      - name: views
        data_tests:
          - not_null
          # Built-in test: Ensures views are never negative (similar to your custom test)
          - dbt_utils.accepted_range:
              min_value: 0