version: 2

# 1. SOURCE FRESHNESS: Catch scraper failures before models run
sources:
  - name: raw_telegram
    database: medical_warehouse
    schema: raw
    tables:
      - name: telegram_data
        freshness:
          warn_after: {count: 24, period: hour}
          error_after: {count: 48, period: hour}
        loaded_at_field: scraped_at

models:
  # --- DIMENSIONS ---
  - name: dim_channels
    description: "Verified list of medical Telegram channels being tracked."
    columns:
      - name: channel_key
        description: "Primary key (surrogate) for the channel."
        data_tests:
          - unique
          - not_null
      - name: channel_name
        description: "The unique handle of the Telegram channel."
        data_tests:
          - unique
          - not_null

  - name: dim_dates
    description: "Standard date dimension for time-series analysis in FastAPI."
    columns:
      - name: date_key
        data_tests:
          - unique
          - not_null

  # --- FACTS ---
  - name: fct_messages
    description: "Central fact table containing enriched message analytics and YOLO metadata."
    columns:
      - name: message_id
        data_tests:
          - unique
          - not_null
      - name: channel_key
        description: "FK to dim_channels. Ensures every message belongs to a known source."
        data_tests:
          - not_null
          - relationships:
              to: ref('dim_channels')
              field: channel_key
      - name: date_key
        description: "FK to dim_dates. Essential for the Activity Trend API."
        data_tests:
          - not_null # Added for resilience
          - relationships:
              to: ref('dim_dates')
              field: date_key
      - name: view_count
        description: "Total views. Must be 0 or higher."
        data_tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0

  # --- STAGING ---
  - name: stg_telegram_messages
    description: "Cleaned version of raw scraper output."
    columns:
      - name: message_id
        data_tests:
          - unique
          - not_null
      - name: views
        data_tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0